CREATE USER pokemon
IDENTIFIED BY p4ssw0rd
DEFAULT TABLESPACE users
TEMPORARY TABLESPACE temp
QUOTA 10M ON users;

GRANT CONNECT TO pokemon;
GRANT RESOURCE TO pokemon;
GRANT CREATE SESSION TO pokemon;
GRANT CREATE TABLE TO pokemon;
GRANT CREATE VIEW TO pokemon;

